
[keys.names]

fullname = [
    { name = "Imiona i nazwisko", surname_at_end = true, extract_names = true },
    { name = "firstLastName", surname_at_end = true, extract_names = true }
]

names = [
    { name = "Imiona" },
    { name = "firstName" }
]

surname = [
    { name = "Nazwisko" },
    { name = "lastName" }
]

[keys.dates]

birthdate = [
    "birthDate",
    "Data urodzenia"
]


# Potential enhanced syntax if date is a part of complex field
# { name = "Data i miejsce urodzenia", date_at_end = false}